on:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build-sample-project:
    name: Build sample project
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.1.1

      fail-fast: false
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install all deps
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: make test
